package br.com.fretee.freteebackend.frete.enums;

public enum StatusFrete {
    SOLICITANDO,
    SOLICITACAO_RECUSADA,
    SOLICITACAO_CANCELADA,
    PRECO_INFORMADO,
    PRECO_RECUSADO,
    AGENDADO,
    CANCELADO,
    CONTRATANTE_FINALIZOU,
    PRESTADOR_SERVICO_FINALIZOU,
    FINALIZADO
}
